[project]
preview = ["pixi-build"]
channels = ["conda-forge", "nodefaults"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]


[environments]
doc = { features = [
  "doc",
], solve-group = "doc" }

[dependencies]
python = "*"
numpy = "*"
pandas = "*"

git = "*" # needed for dynamic versioning

[pypi-dependencies]
xarray = { path = ".", editable = true }


[feature.doc.dependencies]
cfgrib = "*"
kerchunk = "*"
ipykernel = "*"
ipywidgets = "*"                   # silence nbsphinx warning
ipython = '*'
jupyter_client = '*'
jupyter_sphinx = '*'
nbsphinx = '*'
ncdata = '*'
pydata-sphinx-theme = "*"
pyproj = "*"
rich = "*"                         # for Zarr tree()
setuptools = "*"
sphinx-autosummary-accessors = "*"
sphinx-copybutton = "*"
sphinx-design = "*"
sphinx-inline-tabs = "*"
sphinx = ">=6,<8"
sphinxcontrib-mermaid = "*"
sphinxcontrib-srclinks = "*"
sphinx-remove-toctrees = "*"
sphinxext-opengraph = "*"
sphinxext-rediraffe = "*"


[package]
name = "xarray"
version = "dynamic" # dynamic versioning needs better support in pixi https://github.com/prefix-dev/pixi/issues/2923#issuecomment-2598460666 . Putting `version = "dynamic"` here for now until pixi recommends something else.

[package.build]
backend = { name = "pixi-build-python", version = "==0.3.2" }

[package.host-dependencies]
setuptools = "*"
setuptools_scm = "*"
