name: xarray-benchmark
channels:
  - conda-forge
  - nodefaults
dependencies:
  - bottleneck
  - cftime
  - dask-core
  - distributed
  - flox
  - netcdf4
  - numba
  - numbagg
  - numexpr
  - opt_einsum
    - pyarrow # pandas raises a deprecation warning without this, breaking doctests
  - sparse
  - scipy
  - toolz
  - zarr
